### ISSUE TITLE
Should we kill the isolate task manually in case of exceptions?

### ISSUE THREAD

**Issue by srix55** [Renesanse/worker_manager#47]
I noticed that whenever the isolate-function throws an error, the isolate task itself isn't terminated and continues to run indefinitely. Is that required behavior? Should we be killing off the task ourselves after exception handling?

```dart
import 'package:flutter_test/flutter_test.dart';
import 'package:worker_manager/worker_manager.dart';

// This is to demonstrate that the isolate is not terminated after an exception
Future<void> _isolateTask(String? name) async {
  await Future.delayed(const Duration(milliseconds: 1000));
  return Future.error("MyCustomException");
}

void main() {
  test('', () async {
    await Executor().warmUp(log: true);
    try {
      await Executor().execute(arg1: 'test', fun1: _isolateTask);
    } catch (e) {
      print('Caught error: $e');
    }
    await Future.delayed(const Duration(seconds: 15));
  });
}
```
Output
```
3 has been spawned
initialized
added task with number -9007199254740992
isolate with task number -9007199254740992 begins work
Caught error: MyCustomException
```

I am running this on Linux (Fedora 35), Flutter 2.5.3 stable. Noticed this after seeing my new isolate task waiting to start after getting exceptions from running tasks.

**Comment by Renesanse** [comment]
Isolate is just an instrument to run code separately from main isolate, if you getting error while your function run, it is expected behavior. No reason to kill isolate and spawn a new one if exact isolate can execute another task. Btw, spawning isolate is cpu intensive task and that's why I recommend run warmup function before flutter application started. Killing isolate is a little bit dirty way to interrupt something in dart runtime. It is probably can be equivalent to java's Thread.interrupt

**Comment by Renesanse** [comment]
@srix55 please close the issue if explanation satisfied you, thx

**Comment by srix55** [comment]
I was always killing isolate after task completion... Thanks for the clarification 👍
